#!/bin/bash

# crontab -e on childcount user
# on childcount host.
#
# # reverse ssh tunnel keep-alive
# */3 * * * * /bin/bash /usr/bin/reverse_ssh

COMMAND="ssh -N -f -R linode.mvpafrica.org:2210:localhost:22 linode.mvpafrica.org"
ps ax |grep "$COMMAND" |grep -v "grep" > /dev/null 2>&1 || $COMMAND > /dev/null 2>&1
