#!/bin/sh

# crontab -e on childcount user
# on childcount host.
# */3 * * * * /bin/sh /usr/bin/reverse_ssh
COMMAND="ssh -N -f -R linode.mvpafrica.org:2210:localhost:22 linode.mvpafrica.org"
pgrep -f -x "$COMMAND" > /dev/null 2>&1 || $COMMAND
